version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:7.17.3
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
    volumes:
      - es-test-index:/usr/share/elasticsearch/data
      - ./wordnet:/usr/share/elasticsearch/config/synonyms

  kibana:
    image: kibana:7.17.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  jupyter:
    build:
      context: ./
      dockerfile: ./jupyter-docker/Dockerfile
    user: root
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_TOKEN: "docker"
    ports:
      - 8888:8888
    volumes:
      - ./:/project

volumes:
  es-test-index:
