version: "3.9"

services:
  elasticsearch:
    container_name: elasticsearch_service
    image: elasticsearch:7.17.3
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
    volumes:
      - es-test-index:/usr/share/elasticsearch/data
      - ./wordnet:/usr/share/elasticsearch/config/synonyms

  kibana:
    container_name: kibana_service
    image: kibana:7.17.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  jupyter:
    container_name: jupyter_service
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./:/project

volumes:
  es-test-index:
